data1.df<-read.table(file="household_power_consumption.txt", sep=";", header = TRUE, stringsAsFactors = FALSE)
data2.df<-rbind(subset(data1.df, Date == "1/2/2007"),subset(data1.df, Date == "2/2/2007"))
png(filename="plot4.png", width = 480, height = 480, units = "px")
par(mfrow=c(2,2), mar=c(4,4,1,0.5))
with(data2.df, plot(Global_active_power,type="l", xaxt="n", ylab="Global Active Power (kilowatts)", xlab=""))
axis(1,c(1,nrow(data4)/2, nrow(data4)),c("Thu","Fri","Sat"))
with(data2.df, plot(Voltage,type="l", xaxt="n", ylab="Voltage", xlab="datetime"))
axis(1,c(1,nrow(data4)/2, nrow(data4)),c("Thu","Fri","Sat"))
with(data2.df, plot(Sub_metering_1,type="l", xaxt="n", ylab="Energy sub metering", xlab=""))
with(data2.df, lines(Sub_metering_2, col="red"))
with(data2.df, lines(Sub_metering_3, col="blue"))
axis(1,c(1,nrow(data4)/2, nrow(data4)),c("Thu","Fri","Sat"))
legend("topright", c("Sub_metering_1", "Sub_metering_2", "Sub_metering_3"), col=c("black","red","blue"), lwd=1, border="white", cex=1)
with(data2.df, plot(Global_reactive_power,type="l", xaxt="n", xlab="datetime"))
axis(1,c(1,nrow(data4)/2, nrow(data4)),c("Thu","Fri","Sat"))
dev.off()