data1.df<-read.table(file="household_power_consumption.txt", sep=";", header = TRUE, stringsAsFactors = FALSE)
data2.df<-rbind(subset(data1.df, Date == "1/2/2007"),subset(data1.df, Date == "2/2/2007"))
png(filename="plot3.png", width = 480, height = 480, units = "px")
with(data2.df, plot(Sub_metering_1,type="l", xaxt="n", ylab="Energy sub metering", xlab=""))
with(data2.df, lines(Sub_metering_2, col="red"))
with(data2.df, lines(Sub_metering_3, col="blue"))
axis(1,c(1,nrow(data4)/2, nrow(data4)),c("Thu","Fri","Sat"))
legend("topright", c("Sub_metering_1", "Sub_metering_2", "Sub_metering_3"), col=c("black","red","blue"), lwd=1, cex=1)
dev.off()